# for Unet use following
model:
  name: "unet"

  params:
    in_channels: 3
    num_classes: 1

    encoder_channels: [64, 128, 256, 512]
    bottleneck_channels: 1024

    use_batchnorm: true
    bilinear: true

    aux_heads:
      boundary: true